routes/web.php
<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\DepartmentController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('login');
});


Route::get('/login', [AuthController::class, 'login'])->name('login');
Route::post('/login', [AuthController::class, 'login'])->name('login');
Route::get('/forgot-password', [AuthController::class, 'forgotPassword'])->name('forgot_password');
Route::post('/forgot-password', [AuthController::class, 'forgotPassword'])->name('forgot_password');
Route::get('change-language', [AuthController::class, 'changeLanguage'])->name('changeLanguage');


Route::group(['middleware' => ['auth']], function () {
    Route::get('/logout', [AuthController::class, 'logout'])->name('logout');
    Route::get('/change_password', [ProfileController::class, 'changePassword'])->name('changePassword');
    Route::post('/change_password/store', [ProfileController::class, 'changePassword'])->name('changePasswordCustom');
    Route::group(['middleware' => ['check-first-login']], function () {
        Route::get('/profile', [ProfileController::class, 'show'])->name('profile');
        Route::get('/profile/edit', [ProfileController::class, 'edit'])->name('profile.edit');
        Route::post('/profile', [ProfileController::class, 'update'])->name('profile.update');

        Route::post('/upload/store', [ProfileController::class, 'changeAvatar']);
        Route::group(['middleware' => ['verified-account']], function () {
            Route::group(['prefix' => 'employees'], function () {
                Route::get('/', [EmployeeController::class, 'index'])->name('employees.index');
                Route::get('/search', [EmployeeController::class, 'search'])->name('search');
                Route::get('/export-csv', [EmployeeController::class, 'exportCsv']);
                Route::group(['middleware' => ['verified-admin']], function () {
                    Route::get('/create', [EmployeeController::class, 'create'])->name('employees.create');
                    Route::post('/', [EmployeeController::class, 'store'])->name('employees.store');
                    Route::get('/import', [EmployeeController::class, 'import'])->name('import');
                    Route::post('/import-csv', [EmployeeController::class, 'importCsv'])->name('import-csv');
                    Route::get('/{user}/edit', [EmployeeController::class, 'edit'])->name('employees.edit');
                    Route::put('/{user}', [EmployeeController::class, 'update'])->name('employees.update');
                    Route::delete('/{user}', [EmployeeController::class, 'destroy'])->name('employees.destroy');
                });

                Route::get('/{user}', [EmployeeController::class, 'show'])->name('employees.show');
            });
            Route::group(['middleware' => ['verified-admin'], 'prefix' => 'departments', 'as' => 'departments.'], function () {
                Route::get('/', [DepartmentController::class, 'index'])->name('index');
                Route::get('/create', [DepartmentController::class, 'create'])->name('create');
                Route::post('/', [DepartmentController::class, 'store'])->name('store');
                Route::get('/{department}/edit', [DepartmentController::class, 'edit'])->name('edit');
                Route::put('/{department}', [DepartmentController::class, 'update'])->name('update');
                Route::delete('/{department}', [DepartmentController::class, 'destroy'])->name('destroy');
            });
        });
        Route::group(['middleware' => ['verified-admin']], function () {
            Route::post('/reset/password', [AuthController::class, 'forgotPassword'])->name('resetPassword');
        });
    });
});

app/Models/Department.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

/**
 * Department model
 *
 * @property int $id
 * @property string $name
 * @property string $description
 * @property string $created_at
 * @property string $updated_at
 */
class Department extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'description',
    ];

    /**
     * Relationship 1 Department - N User
     *
     * @return HasMany
     */
    public function users(): HasMany
    {
        return $this->hasMany(User::class, 'department_id', 'id');
    }
}

app/Http/Controllers/DepartmentController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\DepartmentRequest;
use App\Services\DepartmentService;
use App\Models\Department;
use App\Services\EmployeeService;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\RedirectResponse;
use Illuminate\View\View;

class DepartmentController extends BaseController
{
    private DepartmentService $departmentService;
    private EmployeeService $employeeService;

    /**
     * Constructor
     *
     * @param DepartmentService $departmentService
     * @param EmployeeService $employeeService
     */
    public function __construct(DepartmentService $departmentService, EmployeeService $employeeService)
    {
        $this->departmentService = $departmentService;
        $this->employeeService = $employeeService;
    }

    /**
     * Display view department list
     *
     * @return View
     */
    public function index(): View
    {
        $departments = $this->departmentService->search();

        return view('departments.index', compact('departments'));
    }

    /**
     * Display view create a department
     *
     * @return View
     */
    public function create(): View
    {
        return view('departments.create');
    }

    /**
     * Create new department
     *
     * @param DepartmentRequest $request
     * @return RedirectResponse
     */
    public function store(DepartmentRequest $request): RedirectResponse
    {
        $result = $this->departmentService->create($request->only(['name', 'description']));

        return $result
            ? redirect()->route('departments.index')->with('success', __('messages.insert_department_success'))
            : redirect()->route('departments.index')->with('error', __('messages.insert_department_fail'));
    }

    /**
     * Display view edit a department
     *
     * @param Department $department
     * @return View
     */
    public function edit(Department $department): View
    {
        $users = $this->employeeService->listEmployeesInDepartment($department->id);

        return view('departments.edit', compact('department', 'users'));
    }

    /**
     * Update a department
     *
     * @param Department $department
     * @param DepartmentRequest $request
     * @return RedirectResponse
     */
    public function update(Department $department, DepartmentRequest $request): RedirectResponse
    {
        $this->departmentService->update($department->id, $request->all());

        return redirect()->route('departments.index')->with('success', __('messages.update_department_success'));
    }

    /**
     * Delete a department
     *
     * @param Department $department
     * @return JsonResponse
     */
    public function destroy(Department $department): JsonResponse
    {
        $result = $this->departmentService->delete($department->id);

        return $result
            ? $this->success(['message' => __('messages.delete_department_success')])
            : $this->error(['message' => __('messages.delete_department_fail')]);
    }
}

resources/views/departments/create.blade.php
@extends('layout.app')
@section('title')
    {{ __('department.add_department') }}
@endsection
@section('content')
<div class="wrapper">
    @include('layout.navbar')
    <div class="content-wrapper">
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>{{ __('department.add_department') }}</h1>
                    </div>
                </div>
            </div>
        </section>

        <section class="content">
            <form action="{{ route('departments.store') }}" method="POST">
                @csrf
                <div class="row">
                    <div class="col-md-6">
                        <div class="card card-primary">
                            <div class="card-header">
                                <h3 class="card-title">{{ __('department.add') }}</h3>
                            </div>
                            <div class="card-body">
                                {{-- Name --}}
                                <div class="form-group required">
                                    <label class="control-label" for="name">{{ __('department.name') }}</label>
                                    <input type="text" name="name" id="name" value="{{ old('name') }}"
                                        class="form-control {!! $errors->has('name') ? 'error' : '' !!}">
                                    @if ($errors->has('name'))
                                        <span class="text-danger">{{ $errors->first('name') }}</span>
                                    @endif
                                </div>

                                {{-- Description --}}
                                <div class="form-group">
                                    <label class="control-label" for="description">{{ __('department.description') }}</label>
                                    <textarea name="description" id="description" rows="4" class="form-control">{{ old('description') }}</textarea>
                                    @if ($errors->has('description'))
                                        <span class="text-danger">{{ $errors->first('description') }}</span>
                                    @endif
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-6">
                        <a href="{{ route('departments.index') }}" class="btn btn-secondary">{{ __('users.cancel') }}</a>
                        <button type="submit" class="btn btn-success float-right">{{ __('department.add') }}</button>
                    </div>
                </div>
            </form>
        </section>
    </div>
</div>
@stop

resources/views/departments/edit.blade.php
@extends('layout.app')
@section('title')
    {{ __('department.edit_department') }}
@endsection
@section('content')
<div class="wrapper">
    @include('layout.navbar')
    <div class="content-wrapper">
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>{{ __('department.edit_department') }}</h1>
                    </div>
                </div>
            </div>
        </section>

        <section class="content">
            <form action="{{ route('departments.update', $department->id) }}" method="post">
                @csrf
                @method('PUT')
                <div class="row">
                    <div class="col-md-6">
                        <div class="card card-primary">
                            <div class="card-header">
                                <h3 class="card-title">{{ __('department.edit') }}</h3>
                            </div>
                            <div class="card-body">
                                {{-- Name --}}
                                <div class="form-group required">
                                    <label class="control-label" for="name">{{ __('department.name') }}</label>
                                    <input type="text" name="name" id="name" value="{{ old('name', $department->name) }}"
                                        class="form-control {!! $errors->has('name') ? 'error' : '' !!}">
                                    @if ($errors->has('name'))
                                        <span class="text-danger">{{ $errors->first('name') }}</span>
                                    @endif
                                </div>

                                {{-- Description --}}
                                <div class="form-group">
                                    <label class="control-label" for="description">{{ __('department.description') }}</label>
                                    <textarea name="description" id="description" rows="4" class="form-control">{{ old('description', $department->description) }}</textarea>
                                    @if ($errors->has('description'))
                                        <span class="text-danger">{{ $errors->first('description') }}</span>
                                    @endif
                                </div>

                                {{-- Manager --}}
                                <div class="form-group">
                                    <label for="manager_id">{{ __('department.manager') }}</label>
                                    <select class="select2" style="width: 100%;" name="manager_id" id="manager_id">
                                        <option value="">{{ __('department.select_manager') }}</option>
                                        @foreach ($users as $user)
                                            <option value="{{ $user->id }}" {{ $user->id == old('manager_id', $user->isManager()) ? 'selected' : '' }}>
                                                {{ $user->name }}
                                            </option>
                                        @endforeach
                                    </select>
                                    @if ($errors->has('manager_id'))
                                        <span class="text-danger">{{ $errors->first('manager_id') }}</span>
                                    @endif
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-6">
                        <a href="{{ route('departments.index') }}" class="btn btn-secondary">{{ __('users.cancel') }}</a>
                        <button type="submit" class="btn btn-success float-right">{{ __('department.save') }}</button>
                    </div>
                </div>
            </form>
        </section>
    </div>
</div>
@stop

resources/views/departments/index.blade.php
@extends('layout.app')
@section('title')
    {{ __('department.list_department') }}
@endsection
@section('content')
<div class="wrapper">
    @include('layout.navbar')
    <div class="content-wrapper">
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>{{ __('department.list_department') }}</h1>
                    </div>
                </div>
            </div>
        </section>
        <section class="content">
            <div class="card">
                <div class="card-header">
                    <a class="btn btn-primary" href="{{ route('departments.create') }}">{{ __('department.add_department') }}</a>
                </div>
                <div class="card-body p-0">
                    <table class="table table-striped projects">
                        <thead>
                            <tr>
                                <th style="width: 20%">{{ __('department.name') }}</th>
                                <th style="width: 40%">{{ __('department.description') }}</th>
                                <th style="width: 25%">{{ __('department.manager') }}</th>
                                <th style="width: 15%">{{ __('department.action') }}</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($departments as $department)
                                @php /** @var App\Models\Department $department */ @endphp
                                <tr>
                                    <td>
                                        <span>{{ $department->name }}</span>
                                    </td>
                                    <td>
                                        <div style="max-height: 200px">{!! nl2br(e($department->description)) !!}</div>
                                    </td>
                                    <td>
                                        <span>{{ $department->manager_name }}</span>
                                    </td>
                                    <td class="project-actions">
                                        <a type="button" class="btn btn-info btn-sm" href="{{ route('departments.edit', $department->id) }}">
                                            <i class="fas fa-pencil-alt"></i> {{ __('department.edit') }}
                                        </a>
                                        <a type="button" class="btn btn-danger btn-sm"
                                            onclick="removeDepartment('{{ route('departments.destroy', $department->id) }}', '{{ __('department.confirm_delete') }}')">
                                            <i class="fas fa-trash"></i> {{ __('department.delete') }}
                                        </a>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
                <div class="card-footer d-flex justify-content-between">
                    <p style="font-size: 1.25rem" class="record">
                        @php
                            $current_page = $departments->toArray()['current_page'];
                            $per_page = $departments->toArray()['per_page'];
                            $total = $departments->toArray()['total'];

                            $first_item = ($current_page - 1) * $per_page + 1;
                            $last_item = $current_page * $per_page > $total ? $total : $current_page * $per_page;

                            echo('Page ' . $current_page . ': ' . $first_item . '~' . $last_item . ' / ' . $total . ' ');
                        @endphp
                        {{__('profile.department')}}
                    </p>
                    {!! $departments->appends(request()->except('page'))->render() !!}
                </div>
            </div>
        </section>
    </div>
</div>
@stop