routes/web.php
<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\DepartmentController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('login');
});


Route::get('/login', [AuthController::class, 'login'])->name('login');
Route::post('/login', [AuthController::class, 'login'])->name('login');
Route::get('/forgot-password', [AuthController::class, 'forgotPassword'])->name('forgot_password');
Route::post('/forgot-password', [AuthController::class, 'forgotPassword'])->name('forgot_password');
Route::get('change-language', [AuthController::class, 'changeLanguage'])->name('changeLanguage');


Route::group(['middleware' => ['auth']], function () {
    Route::get('/logout', [AuthController::class, 'logout'])->name('logout');
    Route::get('/change_password', [ProfileController::class, 'changePassword'])->name('changePassword');
    Route::post('/change_password/store', [ProfileController::class, 'changePassword'])->name('changePasswordCustom');
    Route::group(['middleware' => ['check-first-login']], function () {
        Route::get('/profile', [ProfileController::class, 'show'])->name('profile');
        Route::get('/profile/edit', [ProfileController::class, 'edit'])->name('profile.edit');
        Route::post('/profile', [ProfileController::class, 'update'])->name('profile.update');

        Route::post('/upload/store', [ProfileController::class, 'changeAvatar']);
        Route::group(['middleware' => ['verified-account']], function () {
            Route::group(['prefix' => 'employees'], function () {
                Route::get('/', [EmployeeController::class, 'index'])->name('employees.index');
                Route::get('/search', [EmployeeController::class, 'search'])->name('search');
                Route::get('/export-csv', [EmployeeController::class, 'exportCsv']);
                Route::group(['middleware' => ['verified-admin']], function () {
                    Route::get('/create', [EmployeeController::class, 'create'])->name('employees.create');
                    Route::post('/', [EmployeeController::class, 'store'])->name('employees.store');
                    Route::get('/import', [EmployeeController::class, 'import'])->name('import');
                    Route::post('/import-csv', [EmployeeController::class, 'importCsv'])->name('import-csv');
                    Route::get('/{user}/edit', [EmployeeController::class, 'edit'])->name('employees.edit');
                    Route::put('/{user}', [EmployeeController::class, 'update'])->name('employees.update');
                    Route::delete('/{user}', [EmployeeController::class, 'destroy'])->name('employees.destroy');
                });

                Route::get('/{user}', [EmployeeController::class, 'show'])->name('employees.show');
            });
            Route::group(['middleware' => ['verified-admin'], 'prefix' => 'departments', 'as' => 'departments.'], function () {
                Route::get('/', [DepartmentController::class, 'index'])->name('index');
                Route::get('/create', [DepartmentController::class, 'create'])->name('create');
                Route::post('/', [DepartmentController::class, 'store'])->name('store');
                Route::get('/{department}/edit', [DepartmentController::class, 'edit'])->name('edit');
                Route::put('/{department}', [DepartmentController::class, 'update'])->name('update');
                Route::delete('/{department}', [DepartmentController::class, 'destroy'])->name('destroy');
            });
        });
        Route::group(['middleware' => ['verified-admin']], function () {
            Route::post('/reset/password', [AuthController::class, 'forgotPassword'])->name('resetPassword');
        });
    });
});

resources/views/layout/app.blade.php
<!DOCTYPE html>
<html lang="vi">
<head>
    <title>
        @yield('title')
    </title>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/croppie/2.6.5/croppie.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.css">

    <link rel="stylesheet" href="{{ asset('/template/plugins/fontawesome-free/css/all.min.css') }}" />
    <link rel="stylesheet" href="{{ asset('/template/plugins/icheck-bootstrap/icheck-bootstrap.min.css') }}" />
    <link rel="stylesheet" href="{{ asset('/template/plugins/select2/css/select2.min.css') }}" />
    <link rel="stylesheet" href="{{ asset('/template/dist/css/adminlte.min.css') }}" />
    <link rel="stylesheet" href="{{ asset('/css/app.css') }}" />

    @yield('min-css')
</head>
<body>
    <main>
        @yield('content')
    </main>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/croppie/2.6.5/croppie.min.js"></script>
    <script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script>
    <script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/additional-methods.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="https://kit.fontawesome.com/dfbaedb840.js" crossorigin="anonymous"></script>
    <script src="{{ asset('/template/plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
    <script src="{{ asset('/template/plugins/select2/js/select2.full.min.js') }}"></script>
    <script src="{{ asset('/template/dist/js/adminlte.min.js') }}"></script>
    <script src="{{ asset('/js/main.js') }}"></script>
    <script src="{{ asset('/js/cropper.js') }}"></script>

    <script type="text/javascript">
        var request = window.location;
        $('ul.nav-sidebar a').filter(function () {
            return this.href == request;
        }).addClass('active');

        $('ul.nav-treeview a').filter(function () {
            return this.href == request;
        }).parentsUntil(".nav-sidebar > .nav-treeview")
            .css({'display': 'block'})
            .addClass('menu-open').prev('a')
            .addClass('active');
        
        var url = "{{ route('changeLanguage') }}";

        $(".changeLang").change(function() {
            window.location.href = url + "?lang=" + $(this).val();
        });

        $(function(){
        @if(Session::has('error'))
            toastr.error("{{ Session::get('error') }}");
        @endif

        @if(Session::has('success'))
            toastr.success("{{ Session::get('success') }}");
        @endif
        });
        $(function() {
            $('.select2').select2()
        });

        @if(Auth::user() && Auth::user()->role == config('common.ROLE_EMPLOYEE'))
            $(document.body).attr('class', 'sidebar-collapse');
        @endif
    </script>
    @yield('min-script')
</body>
</html>

resources/views/layout/modal_crop.blade.php
<div id="imageModel" class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">{{ __('profile.change_avatar') }}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div id="image_demo" style="width:350px; margin-top:30px"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary crop_image">{{ __('profile.save') }}</button>
                <button type="button" class="btn btn-secondary" id="btn-close" data-dismiss="modal">
                    {{ __('profile.cancel') }}
                </button>
            </div>
        </div>
    </div>
</div>

resources/views/layout/navbar.blade.php
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" href="#" role="button"
               @if (auth()->user()->isAdmin() || auth()->user()->isManager()) data-widget="pushmenu" @endif>
                <i class="fas fa-bars"></i>
            </a>
        </li>
    </ul>
    <ul class="navbar-nav ml-auto">
        <li class="nav-item mx-4">
            <div class="form-group" style="margin-bottom: 0%">
                <select class="nav-link form-control custom-select changeLang mx-2" id="language" name="language">
                    <option value="en" {{ session()->get('locale') == 'en' ? 'selected' : '' }}>English</option>
                    <option value="vn" {{ session()->get('locale') == 'vn' ? 'selected' : '' }}>Vietnam</option>
                </select>
            </div>
        </li>
        <li class="nav-item dropdown">
            <div class="nav-link pt-auto" style="padding-top: 3px" data-toggle="dropdown" href="#">
                <div class="user-panel d-flex">
                    <div class="image" style="cursor: pointer">
                        <img src="{{ auth()->user()->getAvatarLink() }}" class="img-circle" alt="User Image">
                    </div>
                    <div class="info">
                        <a href="#" class="text-dark">{{ auth()->user()->name }} ({{auth()->user()->department->name}})</a>
                    </div>
                </div>
            </div>
            <div class="dropdown-menu dropdown-menu-right">
                <a type="button" href="{{ route('profile.edit') }}" class="dropdown-item">
                    <i class="fas fa-user-pen mr-2"></i> {{ __('profile.edit_profile') }}
                </a>
                <a type="button" href="{{ route('changePassword') }}" class="dropdown-item">
                    <i class="fas fa-lock mr-2"></i> {{ __('profile.change_password') }}
                </a>
                <a type="button" href="{{ route('logout') }}" class="dropdown-item">
                    <i class="fas fa-sign-out mr-2"></i> {{ __('profile.logout') }}
                </a>
        </li>
    </ul>
</nav>

@if (auth()->user()->isAdmin() || auth()->user()->isManager())
    <aside class="main-sidebar sidebar-dark-primary elevation-4">
        <div class="sidebar">
            <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                <div class="image">
                    <img src="{{ auth()->user()->getAvatarLink() }}" class="img-circle elevation-2" alt="User Image">
                </div>
                <div class="info">
                    <a href="#" class="d-block">{{ auth()->user()->name }}</a>
                </div>
            </div>
            <nav class="mt-2">
                <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu"
                    data-accordion="false">
                    <li class="nav-item">
                        <a href="{{ route('profile') }}" class="nav-link">
                            <i class="nav-icon fas fa-user"></i>
                            <p>{{ __('profile.profile') }}</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link">
                            <i class="nav-icon fas fa-users"></i>
                            <p>
                                {{ __('profile.list_user') }}
                                <i class="fas fa-angle-left right"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">
                            <li class="nav-item">
                                <a href="{{ route('employees.index') }}" class="nav-link">
                                    <i class="far fa-circle nav-icon"></i>
                                    <p>{{ __('users.list_employee') }}</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{{ route('employees.create') }}" class="nav-link">
                                    <i class="far fa-circle nav-icon"></i>
                                    <p>{{ __('users.add_employee') }}</p>
                                </a>
                            </li>
                        </ul>
                    </li>
                    @if (auth()->user()->isAdmin())
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-building-user"></i>
                                <p>
                                    {{ __('profile.department') }}
                                    <i class="fas fa-angle-left right"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a href="{{ route('departments.index') }}" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>{{ __('department.list_department') }}</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="{{ route('departments.create') }}" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>{{ __('department.add_department') }}</p>
                                    </a>
                                </li>
                            </ul>
                        </li>
                    @endif
                </ul>
            </nav>
        </div>
    </aside>
@endif